---
  - hosts: localhost
    connection: local
    tasks:

    - name: Check URL response status
      uri:
        url: "{{ url }}"
      register: result
      ignore_errors: yes
    - set_fact:
        status: "{{ 'Operational' if (result.status == 200) else 'Major Outage' }}"
    
    - name: Send hello world message
      slack:
        token: "{{ token }}"
        channel: ansible-tower-test
        color: 'good'
        attachments:
          - text: "URL: {{ url }} is {{ status }}"
          
