---
  - hosts: localhost
    connection: local
    tasks:

    - name: Send hello world message
      slack:
        token: '{{ token }}'
        channel: ansible-tower-test
        attachments:
          - text: "{{ message }}"
