---
  - hosts: localhost
    connection: local
    tasks:

    - name: Check URL response status
      uri:
        url: "{{ url }}"
      register: result
      ignore_errors: yes
    - set_fact:
        status: "{{ result.status }}"
    
    - name: Send hello world message
      slack:
        token: "{{ token }}"
        channel: ansible-tower-test
        attachments:
          - text: "URL: {{ url }} responded with a status code of {{ status }}"
